# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Twift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Twift
  pod 'ObjectMapper', '~> 2.2'
  pod 'SDWebImage', '~> 4.0'
  pod 'OAuthSwift'
  pod 'Alamofire', '~> 4.5'
end
